spec:
  template:
    spec:
      containers:
        - env:
          - name: example_1
            valueFrom:
              configMapKeyRef:
                  name: example
                  key: example.property.1